# Generated by Django 4.1.1 on 2022-12-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_firehouseaddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupercenterAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supercenter_address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarketAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket_address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
